### PR TITLE
allow setting rest api main route

### PR DESCRIPTION
**Pull request by g-arjones**

### CODE REVIEW

**Comment by doudou** [comment]
CI doesn't pass ... Was /api the current default ?

**Comment by g-arjones** [comment]
[Think so, yes.](https://github.com/rock-core/tools-roby/blob/72bc890cc6b5a80c1e7cfb80494b8eb71f020b9b/lib/roby/interface/rest/server.rb#L43). I will see what's wrong...

**Comment by g-arjones** [comment]
master is failing on my setup as well.. Could you try on yours?

**Comment by doudou** [comment]
Will do. It passes on Travis though ... heisenbug ? https://travis-ci.org/rock-core/tools-roby/jobs/619617552

**Comment by g-arjones** [comment]
> heisenbug ? 

Don't think so.. It fails pretty consistently here... Maybe a behavior change in one of the dependencies?

**Comment by doudou** [comment]
> Maybe a behavior change in one of the dependencies?

Sounds reasonable ...

And you're right. Error 9 [here](https://travis-ci.org/rock-core/tools-roby/jobs/637609058?utm_medium=notification&utm_source=github_status) points to the problem ... Grape started defining (and calling) an "#execute" method but Roby's helpers have one too.

Since one has a block and the other not, we can workaround. Could you take care of it ?
- rename #execute in /home/travis/build/rock-core/tools-roby/lib/roby/interface/rest/helpers.rb to #roby_execute
- define #execute which calls super (i.e. Grape's) if there is no block and roby_execute otherwise
- warn about deprecation (and point to roby_execute) in the latter case to phase execute out

**Comment by g-arjones** [comment]
> Could you take care of it ?

Sure :+1:

**Comment by g-arjones** [comment]
There is a heisenbug now I guess:

```console
arjones@tidewise:~/dev/wetpaint/tools/roby$ bundle exec ruby test/tasks/test_external_process.rb 
Roby[WARN]: debugging is disabled because the 'pry' gem cannot be loaded
Run options: --seed 2970

# Running:

.............................F..

Finished in 2.613554s, 12.2439 runs/s, 19.1310 assertions/s.

  1) Failure:
Roby::Tasks::ExternalProcess::redirection#test_0006_redirects both channels to the same file [test/tasks/test_external_process.rb:282]:
--- expected
+++ actual
@@ -1,5 +1 @@
-"E: FIRST LINE
-E: SECOND LINE
-O: FIRST LINE
-O: SECOND LINE
-"
+""


32 runs, 50 assertions, 1 failures, 0 errors, 0 skips
```

Passes on travis though. There is also an occasional unhandled exception in travis logs that is not reported as error, not sure these are related (see travis build logs for the various ruby versions). 

I don't think neither of these are related to the ruby-grape change but I still have to figure out why REST's tests still don't pass on ruby 2.3

**Comment by doudou** [comment]
> still don't pass on ruby 2.3

Yeah. No need. We don't have to support 2.3 anymore since 18.04 has 2.5

**Pull request merged**
