### PR TITLE
Cleanup and bugfix the Client/Server pair in Interface

### PR DESCRIPTION
**Pull request by doudou**
This is a review of Client, now with a near 100% test coverage. The new test suite allowed me to find one or two pretty major bugs.

### CODE REVIEW

**Comment by doudou** [comment]
@gustavoneves12: could you test that one with the simulator ? It should fix some of the issues related to the GUI blocking unnecessarily, as well as synchronization problems between the Syskit IDE and the syskit-based GUIs

**Comment by doudou** [comment]
Wrong manipulation ...

**Comment by gustavoneves12** [comment]
@doudou I tested using the simulation.
It looks good.

To perform the tests I execute the simulation and change the vehicle position using ***dive control***

**Comment by doudou** [comment]
Hi. I've added a few commits, could you test it again ?

**Pull request merged**
