### PR TITLE
Improve exception explanations

### PR DESCRIPTION
**Pull request by gustavoneves12**
@doudou's changes

### CODE REVIEW

**Comment by doudou** [comment]
@gustavoneves12: you closed the PR ...

**Comment by gustavoneves12** [comment]
It is because I did the PR in the fork in the bir account.

**Comment by doudou** [comment]
> It is because I did the PR in the fork in the bir account.

That's not a problem. The target branch should be rock-core/tools-roby

**Comment by gustavoneves12** [comment]
Can I merge this PR? We already test in my machine.

**Comment by doudou** [comment]
> Can I merge this PR? We already test in my machine.

I'd like to have unit tests for it ... so no leave it for now.

**Comment by doudou** [comment]
Superseded by #34

**Pull request closed without merging**
