### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by doudou** [comment]
@gustavoneves12 @dbcesar which tools/roby branch are you running ? Is it this one ?

**Comment by gustavoneves12** [comment]
@doudou I am using [roby3](https://github.com/rock-core/tools-roby/tree/roby3) branch.

**Comment by doudou** [comment]
You're not using the branch with the batch-in-the-shell ?

**Comment by gustavoneves12** [comment]
After updating the system, the branch was changed to roby3, and I didn't back to **batch-in-the-shell**.

**Comment by doudou** [comment]
OK well ... I'll merge this anyways.

**Pull request merged**
