### PR TITLE
Review plan tests and extend replacement operations for filtering

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by g-arjones** [comment]
I'm afraid I can't help much here but I had a look and could not catch anything obvious. Tests.. Yay! 👍

**Comment by doudou** [comment]
> I'm afraid I can't help much here but I had a look and could not catch anything obvious. Tests.. Yay! 👍

Yeah, this is getting deep in the core of Roby ... Transaction-aware graph modification is not exactly the easiest to grasp.

The depressing (but expected) part was starting to run a branch-aware code coverage library (deep-cover) and finding out how badly the branches are covered.

I'm planning on moving this code into a separate "plan transformation" namespace / zone in the codebase to isolate it more, and allow for more specific documentation of the mechanisms involved.

**Comment by g-arjones** [comment]
> I'm planning on moving this code into a separate "plan transformation" namespace / zone in the codebase to isolate it more, and allow for more specific documentation of the mechanisms involved.

That would be awesome

**Comment by doudou** [comment]
I'm merging this now. It's been used "in production" for a while now.

**Pull request merged**
