### PR TITLE
chore: add unit test for transitioning with a child state event on validate state machine

### PR DESCRIPTION
**Pull request by jhonasiv**
# Update

I changed the PR to add a unit test for this transition to serve as an example in the future. We should also update the documentation with an example. See the discussion below for the reasoning.

# Original PR

This can help when the action state machine transitions using another task's event (other than the toplevel task), i.e.

```
action_state_machine :sm do
        first = state foo_def
        second = state bar_def

        final = state final_def

        first.depends_on second

        transition first, second.some_event, final
end
```

One would be able to use:
```
validate_state_machine ... do
    ....
    assert_transitions_to_state(:final, yield_dependencies: true) do |first_state_task, *dependencies|
          second_task = dependencies.select { _1.model.name == "second" }.task
          execute { second_task.some_event.emit }
    end
end
```

### CODE REVIEW

**Review by wvmcastro — COMMENTED** [review]
If the only motivation for this is the given example, I think one should be able to achieve the same with
```ruby
assert_transitions_to_state :final do |first_state_task|
    execute { first_state_task.second_child.some_event.emit }
end

```

can you check if it works please?

**Comment by jhonasiv** [comment]
> If the only motivation for this is the given example, I think one should be able to achieve the same with
> 
> ```ruby
> assert_transitions_to_state :final do |first_state_task|
>     execute { first_state_task.second_child.some_event.emit }
> end
> ```
> 
> can you check if it works please?

Doesnt work as the "second" state is not a child of "first". That would be the case if first was a composition that adds second as a child.

**Comment by doudou** [comment]
> Doesnt work as the "second" state is not a child of "first". That would be the case if first was a composition that adds second as a child.

It is, but you have to pass a `role` to `depends_on` to get access by name.

```
first.depends_on second, role: "second"
```

`{ first_task.second_child.some_event.emit }`

Compositions are a fancy way to create a root task and call `depends_on` on it with the children names.

**Review by doudou — COMMENTED** [review]
> Doesnt work as the "second" state is not a child of "first". That would be the case if first was a composition that adds second as a child.

It is, but you have to pass a `role` to `depends_on` to get access by name.

```
first.depends_on second, role: "second"
```

`{ first_task.second_child.some_event.emit }`

Compositions are a fancy way to create a root task and call `depends_on` on it with the children names.

Even without the role, what you're doing (passing the dependencies) is actually redundant since they are available from the state task already: `state_task.each_child`

**Comment by jhonasiv** [comment]
> > Doesnt work as the "second" state is not a child of "first". That would be the case if first was a composition that adds second as a child.
> 
> It is, but you have to pass a `role` to `depends_on` to get access by name.
> 
> ```
> first.depends_on second, role: "second"
> ```
> 
> `{ first_task.second_child.some_event.emit }`
> 
> Compositions are a fancy way to create a root task and call `depends_on` on it with the children names.
> 
> Even without the role, what you're doing (passing the dependencies) is actually redundant since they are available from the state task already: `state_task.each_child`

Unfortunately that doesnt seem to work. The actions dependencies are not being translated into childs so each_child doesnt return the dependencies from the state machine and adding the role also doesnt make it available from the task. I understand this was the design expectation so...I can look into it and transform this PR into a bug fix?

**Comment by jhonasiv** [comment]
The children are stored in the root task, and not at each TaskWithDependencies, fortunately we already have a way of accessing the root task from ValidateStateMachine. So I will change this PR to just add a unit test showing this functionality instead.

**Review by doudou — APPROVED** [review]

**Pull request merged**
